project:
  type: website
  output-dir: docs

  
bibliography: bibliographie_richard.bib
csl: apa7.csl



website:
  favicon: images/fox.png
  navbar:
    logo: "images/fox.png"
    background: white

  
   
        
  search: true
  page-footer: 
    center: 
      - text: "Impressum"
        href: footerdocs/impressum.qmd
      - text: "Disclaimer"
        href: footerdocs/disclaimer.qmd 
      - text: "Kontakt"
        href: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy  
    left: 
      - text: "PHBern"
        href: https://www.phbern.ch/
    right: 
      - text: <small>Dieses Produkt ist in einem Kontext des Lernens an der PHBern entstanden.</small>
    background: $schwarz1
    foreground: $schwarz4

format:
  html:
    toc: true
    toc-expand: true
    toc-location: right
    toc-depth: 2
    license: "CC BY-SA"
    page-layout: article
    title-block-banner: true
    
      
  revealjs:
    toc: true
    slide-number: false
    chalkboard: true
    toc-title: "Inhalt"
    footer: "[PHBern, Institut Sekundarstufe 1,](https://www.phbern.ch/studium/sekundarstufe-i)  Richard Conrardy, Dozent"
    title-slide-attributes: 
      data-background-image: "images/logo cc-by-sa.svg"
      data-background-size: 12%
      data-background-position: 94% 99%
    fig-align: center
    scrollable: true
    logo: images/fox.png
    hide-inactive-cursor: true
    mermaid:
      theme: neutral

    categories:
      - Präsentationsfolien


  
  pdf:
    subtitle: test

    
author:   
      - name: Richard Conrardy
        orcid: 0009-0004-2063-6898
        id: 00383195
        email: richard.conrardy@phbern.ch

        url: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy
        affiliations:
        - name: University of Teacher Education Bern
          address: Länggassstrasse 35
          city: Bern
          postal-code: 3012
          url: https://www.phbern.ch
          department: Institut Sekundarstufe I
          ror: https://ror.org/05jf1ma54

          
link-external-newwindow: true
fig-align: center
theme: 
  - styles.scss
date-format: "DD.MM.YYYY"